# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=101, primary_key=True, serialize=False)),
                ('play_num', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['address', 'play_num'],
            },
        ),
        migrations.CreateModel(
            name='Jamm',
            fields=[
                ('jamm_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('jamm_date', models.DateTimeField()),
                ('harmony', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-harmony'],
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propose.Address')),
            ],
            options={
                'ordering': ['-play_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('tag_score', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-tag_score'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('track_title', models.CharField(max_length=22)),
                ('is_title', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propose.Track'),
        ),
        migrations.AddField(
            model_name='jamm',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propose.Tag'),
        ),
        migrations.AddField(
            model_name='jamm',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propose.Track'),
        ),
    ]
